<? $suggestions = $this->recommend->getSuggestions(); if (!empty($suggestions)): ?>
  <div class="alert alert-info">
    <p><?=$this->transEsc('switchquery_intro')?></p>
    <ul>
      <? foreach ($suggestions as $desc => $query): ?>
        <li><?=$this->transEsc($desc)?>: <a href="<?=$this->recommend->getResults()->getUrlQuery()->setSearchTerms($query)?>"><?=$this->escapeHtml($query)?></a>.</li>
      <? endforeach; ?>
    </ul>
    <p><?=$this->transEsc('lib_help_intro')?>
	<?if ($this->layout()->userLang === 'cs'):?>
		<a href="https://www.techlib.cz/cs/2832-nasi-specialiste">
	<?else:?>
		<a href="https://www.techlib.cz/en/2718-our-specialists">
	<?endif;?>
		<?=$this->transEsc('librarian_help')?>
	</a>
    </p>
  </div>
<? endif; ?>
