<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $holdings = $this->driver->getRealTimeHoldings();
    $openUrl = $this->driver->openURLActive('holdings') ? $this->driver->getOpenURL() : false;
    $offlineMode = $this->ils()->getOfflineMode();
    // Account for replace_other_urls setting
    $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();

    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>
<? if ($offlineMode == "ils-offline"): ?>
  <div class="alert alert-warning">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->currentPath()?>?login=true&amp;catalogLogin=true"><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->currentPath() . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="placehold modal-link" title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrl): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrl): ?><?=$this->openUrl($openUrl);?><? endif; ?>
<? endif; ?>
<? foreach ($holdings as $holding): ?>
<h3><?=$this->transEsc($holding['location'])?></h3>
<table class="table table-striped" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
<!-- DM - tabulka jednotek, zahlavi -->
  <tr>
        <td>
                <?=$this->transEsc('Status')?>
        </td>
        <td>
                <?=$this->transEsc('Sublibrary')?>
        </td>
        <td>
                <?=$this->transEsc('Location')?>
        </td>
        <td>
                <?=$this->transEsc('LCC Callnumber')?>
        </td>
        <td>
                <?=$this->transEsc('Old Callnumber')?>
        </td>
  </tr>
  <? if (!empty($holding['summary'])): ?>
  <tr>
    <th><?=$this->transEsc("Volume Holdings")?>: </th>
    <td>
      <? foreach ($holding['summary'] as $current): ?>
        <?=$this->escapeHtml($current)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? if (!empty($holding['notes'])): ?>
  <tr>
    <th><?=$this->transEsc("Notes")?>: </th>
    <td>
      <? foreach ($holding['notes'] as $data): ?>
        <?=$this->escapeHtml($data)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>

  <? foreach ($holding['items'] as $row): ?>
    <? $check = (isset($row['check']) && $row['check']); ?>
    <? $checkStorageRetrievalRequest = (isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest']); ?>
    <? $checkILLRequest = (isset($row['checkILLRequest']) && $row['checkILLRequest']); ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
<!--    <th><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>-->
        <td>
          <? if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <? endif; ?>
          <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
	      <? /* Begin Available Items (Holds) */ ?>
	       <link property="availability" href="http://schema.org/InStock" />
               <!-- DM - zobrazeni statusu -->
               <span class="available"><?=$this->transEsc($row['status'])?></span>
              <? if (isset($row['link']) && $row['link']): ?>
                <a style="display:inline-block" class="<?=$check ? 'checkRequest ' : ''?>inlineblock modal-link placehold" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>" title="<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
              <? endif; ?>
              <? if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?>modal-link placeStorageRetrievalRequest" href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>" title="<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <? endif; ?>
              <? if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
                <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>inlineblock modal-link placeILLRequest" href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"  title="<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <span class="text-danger"><?=$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? if (isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> modal-link inlineblock placehold" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              <? endif; ?>
            <? endif; ?>
          <? endif; ?>
          <? /* Embed item structured data: library, barcode, call number */ ?>
          <? if ($row['location']): ?>
            <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
          <? endif; ?>
          <? if ($row['barcode']): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
          <? endif; ?>
          <? if ($row['callnumber']): ?>
            <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
          <? endif; ?>
          <? /* Declare that the item is to be borrowed, not for sale */ ?>
            <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
            <link property="itemOffered" href="#record" />
	</td>
	<!-- DM - dalsi sloupce tabulky jednotek -->
        <td>    <!-- Sublibrary -->
                <?=$this->escapeHtml($row['sub_lib_desc'])?>
        </td>

        <td>    <!-- Location -->
                <?=$this->escapeHtml($row['collection_desc'])?>
        </td>

        <td>    <!-- LCC Callnumber -->
                <?=$this->escapeHtml($row['callnumber_second'])?>
        </td>
        <td>    <!-- Old Callnumber -->
                <?=$this->escapeHtml($row['callnumber'])?>
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>
  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>
